jobs:
  create-open-delete:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: paulroberttaylor@gmail.com
      - sfdx/scratch-create:
          scratch-alias: circleci
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: circleci
      - sfdx/scratch-delete:
          scratch-alias: circleci
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - create-open-delete